name: Deploy to Github Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Lint and format code
        run: npm run lint && npm run format

      - name: Build and deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBKA_TOKEN }}
          REACT_APP_GITHUB_PAGES: true
        run: npm run build && npm run deploy