name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Set Git identity
        run: |
          git config --global user.email "karan1312004@gmail.com"
          git config --global user.name "karansingh2004"
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBKA_TOKEN }}
        run: |
          npm run build
          # git remote set-url origin https://${GITHUB_TOKEN}@github.com/karansingh2004/portfolio.git
          # git config --global user.email "karan1312004@gmail.com"
          # git config --global user.name "karansingh2004"
          # git push --force origin gh-pages
      - name: Deploy to GitHub Pages
        run: npm run deploy