name: Deploy to Github Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        run: |
          docker build -t my-app .
          docker tag my-app ${{ secrets.DOCKER_USERNAME }}/my-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest
      - name: Run tests and build website
        run: |
          docker run -it --rm ${{ secrets.DOCKER_USERNAME }}/my-app:latest npm run test
          docker run -it --rm ${{ secrets.DOCKER_USERNAME }}/my-app:latest npm run build
      - name: Deploy to Github Pages
        uses: actions/checkout@v2
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote add origin https://github.com/${GITHUB_REPO}.git
          git push --force origin main:gh-pages 