name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.GITHUBKA_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        run: |
          docker build -t my-website .
          docker tag my-website $GITHUB_SHA
          docker push $GITHUB_SHA

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_NAME: ${{ github.repository }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git checkout -b gh-pages
          git rm -rf .
          docker run -p 3000:3000 -d $GITHUB_SHA
          docker exec -it $(docker ps -aq) npm run build
          docker exec -it $(docker ps -aq) npm run export
          mv out/* .
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages --force
